# Generated by Django 2.0.3 on 2018-04-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone_num', models.CharField(max_length=255, unique=True, verbose_name='Номер телефона')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикования')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
