# Generated by Django 2.0.3 on 2018-04-02 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180402_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 4, 16, 32, 569146)),
        ),
    ]
