# Generated by Django 2.0.3 on 2018-04-06 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20180406_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 17, 33, 18, 801756)),
        ),
    ]
